<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Leno.Infrastructure</RootNamespace>
    <Description>Leno Infrastructure RateLimiting 子包：限流器</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Leno.Infrastructure.Tests" />
    <InternalsVisibleTo Include="Leno.ApiGateway.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leno.Infrastructure.Abstractions\Leno.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Leno.SharedKernel\Leno.SharedKernel.csproj" />
    <ProjectReference Include="..\Leno.Infrastructure.Caching\Leno.Infrastructure.Caching.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
  </ItemGroup>

</Project>
