// <auto-generated />
using System;
using Leno.ReviewAfterSales.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leno.ReviewAfterSales.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewAfterSalesDbContext))]
    [Migration("20260723131529_AddIxReviewsSellerId")]
    partial class AddIxReviewsSellerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leno.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("PublishingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("publishing_started_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("schema_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outbox_messages_status");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Leno.ReviewAfterSales.Domain.Aggregates.AfterSales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("applied_at");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("ChannelRefundNo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("channel_refund_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("currency");

                    b.Property<string>("FailReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("fail_reason");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("OrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_line_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("reason_category");

                    b.Property<decimal?>("RefundedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refunded_amount");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("refunded_at");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reject_reason");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<DateTime?>("ReturnConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("return_confirmed_at");

                    b.Property<Guid?>("ReturnConfirmedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("return_confirmed_by");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("returned_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("tracking_no");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.Property<string>("_images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_after_sales_order_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_after_sales_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_after_sales_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_after_sales_user_id");

                    b.ToTable("after_sales", (string)null);
                });

            modelBuilder.Entity("Leno.ReviewAfterSales.Domain.Aggregates.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AuditedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("audited_at");

                    b.Property<Guid?>("AuditorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auditor_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("HiddenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hidden_at");

                    b.Property<Guid?>("HiddenBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hidden_by");

                    b.Property<string>("HideReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hide_reason");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_line_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("SellerReplyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("seller_reply_at");

                    b.Property<Guid?>("SellerReplyBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_reply_by");

                    b.Property<string>("SellerReplyContent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("seller_reply_content");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SpuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("spu_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.Property<string>("_images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_order_line_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_reviews_seller_id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SellerId"), new[] { "CreatedAt", "Rating" });

                    b.HasIndex("SpuId")
                        .HasDatabaseName("ix_reviews_spu_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.ToTable("reviews", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
