// <auto-generated />
using System;
using Leno.Order.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leno.Order.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260723190000_AddReadModelSnapshots")]
    partial class AddReadModelSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leno.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("PublishingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("publishing_started_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("schema_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outbox_messages_status");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Leno.Infrastructure.ReadModel.ReadModelSnapshot", b =>
                {
                    b.Property<string>("AggregateId")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasColumnName("aggregate_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_json");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("taken_at");

                    b.HasKey("AggregateId", "Version");

                    b.HasIndex("AggregateType")
                        .HasDatabaseName("ix_read_model_snapshots_aggregate_type");

                    b.ToTable("read_model_snapshots", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Application.ProcessManagers.States.OrderPaymentProcessState", b =>
                {
                    b.Property<Guid>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("current_state");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<bool>("OrderMarkedPaid")
                        .HasColumnType("bit")
                        .HasColumnName("order_marked_paid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<bool>("PointsConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("points_confirmed");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<bool>("StockConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("stock_confirmed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ProcessId");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("ix_order_payment_processes_current_state");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_payment_processes_order_id");

                    b.ToTable("order_payment_processes", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Application.Sagas.States.OrderSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("current_state");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("items_json");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("PointsFrozenAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("points_frozen_amount");

                    b.Property<string>("StockReservationIdsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stock_reservation_ids_json");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("ix_order_saga_states_current_state");

                    b.ToTable("order_saga_states", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.FreightTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("FreeShippingThreshold")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("free_shipping_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_freight_templates_seller_id");

                    b.ToTable("freight_templates", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.LogisticsCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("ServicePhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("service_phone");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<bool>("SupportTracking")
                        .HasColumnType("bit")
                        .HasColumnName("support_tracking");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_logistics_companies_code");

                    b.ToTable("logistics_companies", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AfterSalesWindowEndsAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("after_sales_window_ends_at");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expire_at");

                    b.Property<decimal>("FreightAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("freight_amount");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("ItemsAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("items_amount");

                    b.Property<string>("LogisticsCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogisticsNo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("logistics_no");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("order_no");

                    b.Property<int>("OrderType")
                        .HasColumnType("int")
                        .HasColumnName("order_type");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<bool>("PaymentInitiated")
                        .HasColumnType("bit")
                        .HasColumnName("payment_initiated");

                    b.Property<DateTime?>("PaymentInitiatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_initiated_at");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PointsOffsetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("points_offset_amount");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipped_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TradeNo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("trade_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_orders_is_deleted");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_no");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_orders_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BaseLineQty")
                        .HasColumnType("int")
                        .HasColumnName("base_line_qty");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<int>("DeductedQty")
                        .HasColumnType("int")
                        .HasColumnName("deducted_qty");

                    b.Property<int>("ReservedQty")
                        .HasColumnType("int")
                        .HasColumnName("reserved_qty");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sku_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_reservations_sku_id");

                    b.ToTable("stock_reservations", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.StockReservationCompensation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("last_error_message");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int")
                        .HasColumnName("max_retries");

                    b.Property<int>("OperationType")
                        .HasColumnType("int")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sku_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_stock_compensations_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stock_compensations_status");

                    b.HasIndex("OrderId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_compensations_order_sku_pending")
                        .HasFilter("[status] = 0");

                    b.ToTable("stock_reservation_compensations", (string)null);
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.FreightTemplate", b =>
                {
                    b.OwnsMany("Leno.Order.Domain.ValueObjects.FreightRegionRule", "RegionRules", b1 =>
                        {
                            b1.Property<string>("RegionCode")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("region_code");

                            b1.Property<decimal>("AdditionalPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("additional_price");

                            b1.Property<int>("AdditionalUnit")
                                .HasColumnType("int")
                                .HasColumnName("additional_unit");

                            b1.Property<decimal>("FirstPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("first_price");

                            b1.Property<int>("FirstUnit")
                                .HasColumnType("int")
                                .HasColumnName("first_unit");

                            b1.Property<Guid>("FreightTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RegionCode");

                            b1.HasIndex("FreightTemplateId");

                            b1.ToTable("freight_region_rules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FreightTemplateId");
                        });

                    b.Navigation("RegionRules");
                });

            modelBuilder.Entity("Leno.Order.Domain.Aggregates.Order", b =>
                {
                    b.OwnsMany("Leno.Order.Domain.Aggregates.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("created_by");

                            b1.Property<decimal>("DiscountAllocation")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("discount_allocation");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("sku_id");

                            b1.Property<Guid?>("SourceCartItemId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("source_cart_item_id");

                            b1.Property<decimal>("Subtotal")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("subtotal");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Leno.Order.Domain.ValueObjects.ProductSnapshot", "ProductSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("MainImage")
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)")
                                        .HasColumnName("product_main_image");

                                    b2.Property<string>("ProductName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("product_name");

                                    b2.Property<Guid>("SellerId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("product_seller_id");

                                    b2.Property<Guid>("SkuId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("product_sku_id");

                                    b2.Property<string>("SkuName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("product_sku_name");

                                    b2.Property<Guid>("SpuId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("product_spu_id");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("order_items");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("ProductSnapshot")
                                .IsRequired();
                        });

                    b.OwnsOne("Leno.Order.Domain.ValueObjects.AddressSnapshot", "AddressSnapshot", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("address_detail");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("district");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("province");

                            b1.Property<string>("RecipientName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("recipient_name");

                            b1.Property<string>("RecipientPhone")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("recipient_phone");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("AddressSnapshot")
                        .IsRequired();

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
