// <auto-generated/>
// 全局 using 指令，避免每个测试文件重复声明。
global using System.Net;
global using System.Net.Http.Json;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using FluentAssertions;
global using Leno.Infrastructure.Auth;
global using Leno.SharedContracts.Responses;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
global using Xunit;
