// <auto-generated />
using System;
using Leno.Promotion.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leno.Promotion.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    [Migration("20260722000000_AddUserCouponExchangeId")]
    partial class AddUserCouponExchangeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leno.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("PublishingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("publishing_started_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outbox_messages_status");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Leno.Promotion.Domain.Aggregates.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("FaceValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("face_value");

                    b.Property<int>("IssuedQty")
                        .HasColumnType("int")
                        .HasColumnName("issued_qty");

                    b.Property<decimal>("MinSpend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_spend");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int")
                        .HasColumnName("total_qty");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("ValidDays")
                        .HasColumnType("int")
                        .HasColumnName("valid_days");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_to");

                    b.Property<int>("ValidityType")
                        .HasColumnType("int")
                        .HasColumnName("validity_type");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_coupons_status");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Leno.Promotion.Domain.Aggregates.PromotionActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rules");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_promotion_activities_status");

                    b.ToTable("promotion_activities", (string)null);
                });

            modelBuilder.Entity("Leno.Promotion.Domain.Aggregates.SeckillActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int")
                        .HasColumnName("available_stock");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int>("LimitPerUser")
                        .HasColumnType("int")
                        .HasColumnName("limit_per_user");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("original_price");

                    b.Property<decimal>("SeckillPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("seckill_price");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SpuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("spu_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TotalStock")
                        .HasColumnType("int")
                        .HasColumnName("total_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_seckill_activities_sku_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_seckill_activities_status");

                    b.ToTable("seckill_activities", (string)null);
                });

            modelBuilder.Entity("Leno.Promotion.Domain.Aggregates.SeckillPreOccupationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRolledBack")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PreOccupiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RolledBackAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("IsFulfilled", "IsRolledBack", "PreOccupiedAt");

                    b.ToTable("SeckillPreOccupationRecords", (string)null);
                });

            modelBuilder.Entity("Leno.Promotion.Domain.Aggregates.UserCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("ExchangeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exchange_id");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_at");

                    b.Property<Guid?>("LockedOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("locked_order_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("used_order_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_user_coupons_coupon_id");

                    b.HasIndex("ExchangeId")
                        .IsUnique()
                        .HasFilter("[exchange_id] IS NOT NULL")
                        .HasDatabaseName("ux_user_coupons_exchange_id");

                    b.HasIndex("LockedOrderId")
                        .HasDatabaseName("ix_user_coupons_locked_order_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_coupons_user_id");

                    b.HasIndex("UserId", "CouponId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_coupons_user_id_coupon_id");

                    b.ToTable("user_coupons", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
